// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleLessNamespace {
  export interface IIndexModuleLess {
    btn: string
    'btn-submit': string
    btnSubmit: string
    'form-box': string
    formBox: string
    'input-text': string
    inputText: string
    login: string
  }
}

declare const IndexModuleLessModule: IndexModuleLessNamespace.IIndexModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexModuleLessNamespace.IIndexModuleLess
}

export = IndexModuleLessModule
